### ISSUE TITLE
Couldn't add it to my current chrome 61

### ISSUE THREAD

**Issue by wurtel2** [stevenmirabito/nortel-switch-helper#2]
First, thank you thank you for this! I dispair at those manufacturers who think java or even activeX plugins are a good idea...

I managed to install this plugin on an old virtualbox installation of XP with Chrome 49 (old). Now at least I can configure the switch!

However my main OS is Linux, and the plugin failed to load on Chrome 61.0.3135.4 ("could not unzip"). Could it be a new Chrome or a Linux problem?

**Comment by stevenmirabito** [comment]
Hey! Thanks for reporting this issue.

I've gone ahead and published this extension directly to the Chrome Webstore. You should be able to install it by clicking [here](https://chrome.google.com/webstore/detail/nortel-switch-helper/hfmagjflmeddpfcncichphgjindlidnn).

Let me know if you're still having issues with the published extension.

**Comment by wurtel2** [comment]
On Mon 22 Jan 2018, Steven Mirabito wrote:

> Hey! Thanks for reporting this issue.
> 
> I've gone ahead and published this extension directly to the Chrome Webstore. You should be able to install it by clicking [here](https://chrome.google.com/webstore/detail/nortel-switch-helper/hfmagjflmeddpfcncichphgjindlidnn).
> 
> Let me know if you're still having issues with the published extension.

Thanks, that worked fine now!

I've left a raving review :-)


Paul
